CREATE TABLE dbo.rep_propertiesByAgent (
    -- IDENTIFIERS & CONTEXT
    [Agent_FullName] varchar(350), -- Name of the real estate agent. GROUP BY this for agent performance.
    [Agent_Office] varchar(100), -- The office branch the agent belongs to.
    [Agent_Side] varchar(1), -- 'L' = Listing Side (Seller's agent), 'S' = Selling Side (Buyer's agent).
    [status] varchar(100), -- Current status of the deal. Values: 'Closed', 'Pending', 'Active', 'Cancelled', 'Expired'.

    -- DATES (Time calculations)
    [listDate] date, -- Date when the property was listed on the market.
    [pendingDate] date, -- Date when an offer was accepted.
    [ClosingDate] datetime, -- Date when the transaction was finalized/sold. PRIMARY DATE for "Sales per Year/Month".

    -- FINANCIALS (Sales & Commission)
    [listingPrice] decimal(18, 2), -- Original asking price of the property.
    [sellingPrice] decimal(18, 2), -- Final price the property sold for. WARNING: Do not sum this directly for Agent Performance as it represents the total property value.
    [Agent_Volume] decimal(17, 5), -- The pro-rated sales volume credited to this agent. USE THIS for "Best Agent" or "Sales Volume" calculations.
    [Agent_Gross] decimal(17, 5), -- Gross Commission Income (GCI) generated by this agent on this deal.
    [companyDollarAmount] decimal(17, 5), -- The portion of commission kept by the brokerage (Revenue).

    -- METADATA
    [propertyAddress] varchar(1000), -- Physical address of the property.
    [propertyType] varchar(100), -- Type: Single Family, Condo, Multi-Family, Commercial.
    [city] varchar(100), -- City location of the property.
    [state] varchar(100), -- State location.
    [zip] varchar(100) -- Zip code.
);